# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee1d6ffb9898aebbaa7672c69c93a72da1b5b03c6a25fc6f13c3e359dcfc481d99f0a32749425dfcfce940ba5ef3a64c73ee75b8b7dae12457a4831e31534fdc

test:
  secret_key_base: c2f32736eb0560aed1e2d565b87841aa3c9c768565a6392d0729aea00364e46cbc12ccd2ce3cc954eb881ce68b27444fe9bfe44bd83daf85778c1700c7eedb77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
